server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://pg-d1a458a5-79c5-4b90-8a8c-8332ea73b1c9-productd3159293544-chor.a.aivencloud.com:25731/defaultdb
    username: avnadmin
    password: AVNS_J-xqovcsjkV7zTnbA0G
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop